# Generated by Django 3.1.4 on 2021-01-04 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('alternative_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('data_source', models.TextField()),
                ('security_type', models.PositiveSmallIntegerField(choices=[(1, 'Stock'), (2, 'ETF'), (3, 'Bond'), (4, 'Fund')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.FloatField()),
                ('purchase_time', models.DateTimeField()),
                ('purchase_fee', models.FloatField()),
                ('amount', models.IntegerField()),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('sell_time', models.DateTimeField(blank=True, null=True)),
                ('sell_fee', models.FloatField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='security',
            name='user',
            field=models.ManyToManyField(through='web.UserSecurities', to=settings.AUTH_USER_MODEL),
        ),
    ]
