# Generated by Django 3.1.4 on 2021-03-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210125_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSecurities',
            new_name='UsersSecurities',
        ),
    ]
