# Generated by Django 3.1.4 on 2021-03-03 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210301_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'INCOME'), (2, 'OUTGOINGS')], default=1)),
                ('transacted_at', models.DateField()),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'FEE'), (2, 'SELL'), (3, 'WITHDRAWAL'), (4, 'DIVIDEND'), (5, 'INCOME')], default=1)),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
