# Generated by Django 3.1.4 on 2021-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_usersmoneytransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userssecurities',
            old_name='purchase_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='userssecurities',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='userssecurities',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='userssecurities',
            old_name='purchase_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='userssecurities',
            name='sell_fee',
        ),
        migrations.RemoveField(
            model_name='userssecurities',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='userssecurities',
            name='sell_time',
        ),
        migrations.AddField(
            model_name='userssecurities',
            name='direction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BUY'), (2, 'SELL')], default=1),
        ),
    ]
