# Generated by Django 3.1.4 on 2021-03-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210306_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userssecurities',
            old_name='time',
            new_name='date',
        ),
    ]
