# Generated by Django 3.1.4 on 2021-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210307_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssecurities',
            name='date',
            field=models.DateField(),
        ),
    ]
