# Generated by Django 3.1.4 on 2021-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210331_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
