# Generated by Django 3.1.4 on 2021-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210602_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
