# Generated by Django 3.1.4 on 2021-06-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_exchange_sync_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('shortcut', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='security',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.exchange'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.country'),
        ),
    ]
