# Generated by Django 3.1.4 on 2021-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20210602_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='time_zone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stock'), (2, 'ETF'), (3, 'Bond'), (4, 'Fund'), (5, 'Crypto')], default=1),
        ),
    ]
