# Generated by Django 3.1.4 on 2021-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210629_1505'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_country_name'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_exchange_name'),
        ),
    ]
