# Generated by Django 3.1.4 on 2021-07-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20210702_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('show', models.BooleanField(blank=True, null=True)),
                ('show_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.securitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.securitytype'),
        ),
    ]
