# Generated by Django 3.1.4 on 2021-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210704_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='data_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
