# Generated by Django 3.1.4 on 2021-07-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20210707_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitytype',
            name='show_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.securitytype'),
        ),
    ]
