# Generated by Django 3.1.4 on 2021-07-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20210711_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmoneytransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersmoneytransaction',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.security'),
        ),
        migrations.AlterField(
            model_name='usersmoneytransaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'fee'), (2, 'sell'), (3, 'withdrawal'), (4, 'dividend'), (5, 'deposit'), (5, 'other')], default=1),
        ),
    ]
